### ISSUE TITLE
How to access heroku config vars in the run.sh script

### ISSUE THREAD

**Issue by amritk** [niteoweb/heroku-buildpack-shell#2]
I tried a few things, I can't seem to access the config vars, they don't seem to show up as environment variables.

**Comment by dz0ny** [comment]
To print them all use `env` command. For use, just like you would in standard bash. Note that not all env variables are present, due to how Heroku runs things these days.

**Comment by amritk** [comment]
Yea I just realized the issue is with heroku. 

Thanks
